# Generated by Django 6.0.2 on 2026-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=20)),
                ('player_name', models.CharField(db_column='name', max_length=100)),
                ('player_height', models.FloatField(db_column='height')),
                ('player_weight', models.FloatField(db_column='weight')),
                ('player_matches_played', models.IntegerField(db_column='games')),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
